apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: result
  name: result
spec:
  replicas: 1
  selector:
    matchLabels:
      app: result
  template:
    metadata:
      labels:
        app: result
    spec:
      containers:
      - image: image: 686458136675.dkr.ecr.ap-northeast-1.amazonaws.com/example-voting-app-result:initial
        name: result
        ports:
        - containerPort: 80
          name: result
