apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vote
  name: vote
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vote
  template:
    metadata:
      labels:
        app: vote
    spec:
      containers:
      - image: 686458136675.dkr.ecr.ap-northeast-1.amazonaws.com/example-voting-app-vote:7df42a51842db46357212898209561a23307fbbb
        name: vote
        ports:
        - containerPort: 80
          name: vote
