apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: worker
  name: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - image: 686458136675.dkr.ecr.ap-northeast-1.amazonaws.com/example-voting-app-worker:7df42a51842db46357212898209561a23307fbbb
        name: worker
